language: java
install: mvn -X clean test install
sudo: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: sureshasbe@gmail.com
  password:
    secure: Z5kf5FuCFTUECrIx6Ekguv6jnHtBOYFskReyku/HWt213YNUd8YeS79Gam5IRThAoLJBdh0wvwIalaVafCvYlRdUyTBiPEkTLEERPuTFl5zve9WVOTs7NNLykxxYHzta73Wkmi+7ymbh43okHab4gBG97SwBsAsJjmPuuA+dIo54ooRpb5nveMPAuSoZIrCT7jClzHA+axeX3bgJLAeu6W2J71o8mojY/vwnGgLAtWapRPfJPg+c1XxDaqsaucbblZXLlVcPhlIeib3+xapK+bypBU4EVWVOFVBmqvW250++lvs32kON3ISx2xzGhTQrsR5eTYSVfQM2nbdci986l2Xw0hG4JKyrSBpN16E7GqMrqYCUzJpmmazV1xlOqiNPWCUC5YwDKUWciiWsbnAtopFeJFn9JyouRCxOjZUckT4/9Z2N0JdHBIkrgRGdVqfQFc8YXizfY7jJZrFuew2J8PeXRI3yfym/BQmS6T2gWI21IVbK2efOaOXu1izhvK9iaJzoXxEGoACtaoYeH/Sfzu/PEXIG0eiKODecZoj0W73nq+C5UodF3t8TeYndOc2Rrt6qFJ+Lv6Rw3syUkjVrXRUqMRyIB2wc/ezQmQvELBKEnyEF+HXvluJeDsteaimeYvreozmoWkrCRt+fMrblN+lw3jfFf+av5n8i+qmWQwE=
  organization: Sizzlers
  space: development
